version: "3.7"

services:
    wol:
        container_name: wol
        network_mode: host
        build:
            context: ./
            dockerfile: DockerFile
            target: app
        working_dir: /var/www
        restart: always